name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run tests
      run: mvn test

    - name: Package the application
      run: mvn package -DskipTests

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-jar
        path: target/*.jar
